"""Generate firmware C headers from the trained models.

Produces:
  firmware/mel_filterbank.h  -- librosa mel filterbank (so the board's
                                log-mel matches training exactly)
  firmware/model_meta.h      -- station labels, normalization constants,
                                window sizes, pipeline thresholds

Run:  python scripts/gen_firmware_assets.py
"""
import json
from pathlib import Path

import numpy as np
import librosa

ROOT = Path(__file__).resolve().parent.parent
MODELS = ROOT / "models"
FW = ROOT / "firmware"

meta = json.loads((MODELS / "path1_meta.json").read_text(encoding="utf-8"))
SR = meta["sample_rate"]
N_FFT = meta["n_fft"]
N_MELS = meta["n_mels"]
MEL_HOP = meta["mel_hop"]
N_BINS = N_FFT // 2 + 1
STATIONS = meta["stations"]

# pipeline params (kept identical to scripts/verify_pipeline.py)
SLIDE_HOP_SEC = 0.25
TRIG_THRESH = 0.60
CONF_THRESH = 0.50
NAME_OFFSET_SEC = 1.5
MIN_TRIG_RUN = 3


def gen_mel_filterbank():
    """librosa mel filterbank → C header (dense float matrix)."""
    fb = librosa.filters.mel(sr=SR, n_fft=N_FFT, n_mels=N_MELS)  # (N_MELS, N_BINS)
    out = [
        "// Auto-generated by scripts/gen_firmware_assets.py — do not edit.",
        "// librosa mel filterbank: matches melspectrogram used in training.",
        "#ifndef MEL_FILTERBANK_H",
        "#define MEL_FILTERBANK_H",
        "",
        f"#define MEL_N_MELS {N_MELS}",
        f"#define MEL_N_BINS {N_BINS}",
        "",
        f"static const float mel_filterbank[{N_MELS}][{N_BINS}] = {{",
    ]
    for row in fb:
        vals = ", ".join(f"{v:.8e}f" for v in row)
        out.append(f"  {{{vals}}},")
    out += ["};", "", "#endif // MEL_FILTERBANK_H", ""]
    (FW / "mel_filterbank.h").write_text("\n".join(out), encoding="utf-8")
    return fb.shape


def gen_model_meta():
    """Station labels + constants → C header."""
    names = ",\n  ".join(f'"{s}"' for s in STATIONS)
    out = f"""// Auto-generated by scripts/gen_firmware_assets.py — do not edit.
// Path 1 model metadata: labels, normalization, pipeline thresholds.
#ifndef MODEL_META_H
#define MODEL_META_H

// ---- audio / feature ----
#define SAMPLE_RATE      {SR}
#define N_FFT            {N_FFT}
#define N_MELS           {N_MELS}
#define MEL_HOP          {MEL_HOP}

// ---- window sizes (samples) ----
#define KWS_WIN_SAMPLES  {int(meta['kws_win_sec'] * SR)}   // {meta['kws_win_sec']}s
#define CNN_WIN_SAMPLES  {int(meta['cnn_win_sec'] * SR)}   // {meta['cnn_win_sec']}s
#define KWS_MEL_FRAMES   {1 + int(meta['kws_win_sec'] * SR) // MEL_HOP}
#define CNN_MEL_FRAMES   {1 + int(meta['cnn_win_sec'] * SR) // MEL_HOP}

// ---- per-model log-mel normalization (x = (mel - mean) / std) ----
#define KWS_NORM_MEAN    ({meta['kws_norm_mean']:.8f}f)
#define KWS_NORM_STD     ({meta['kws_norm_std']:.8f}f)
#define CNN_NORM_MEAN    ({meta['cnn_norm_mean']:.8f}f)
#define CNN_NORM_STD     ({meta['cnn_norm_std']:.8f}f)

// ---- pipeline (same as verify_pipeline.py) ----
#define SLIDE_HOP_SAMPLES   {int(SLIDE_HOP_SEC * SR)}   // {SLIDE_HOP_SEC}s KWS slide
#define NAME_OFFSET_SAMPLES {int(NAME_OFFSET_SEC * SR)}   // trigger start -> station name
#define TRIG_THRESH         ({TRIG_THRESH}f)             // KWS trigger probability
#define CONF_THRESH         ({CONF_THRESH}f)             // min CNN confidence
#define MIN_TRIG_RUN        {MIN_TRIG_RUN}               // debounce: consecutive trigger windows

// ---- station labels (CNN output index -> name, UTF-8) ----
#define NUM_STATIONS {len(STATIONS)}
static const char *const STATION_NAMES[NUM_STATIONS] = {{
  {names}
}};

#endif // MODEL_META_H
"""
    (FW / "model_meta.h").write_text(out, encoding="utf-8")


def main():
    FW.mkdir(parents=True, exist_ok=True)
    shape = gen_mel_filterbank()
    gen_model_meta()
    print(f"firmware/mel_filterbank.h  생성  (mel filterbank {shape[0]}x{shape[1]})")
    print(f"firmware/model_meta.h      생성  ({len(STATIONS)}개 역, KWS/CNN 상수)")


if __name__ == "__main__":
    main()
