"""Generate firmware/demo_audio.h — demo announcement clips for Flash.

Path 1 has no microphone: the board replays clips stored in Flash and
runs them through KWS+CNN. STM32 F411RE has only 512 KB Flash, so clips
are short (just the Korean announcement) and few.

Run:  python scripts/gen_demo_audio.py
"""
import sys
import wave
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
WAV = ROOT / "data" / "processed" / "wav"
OUT = ROOT / "firmware" / "demo_audio.h"

SR = 16000
CLIP_SEC = 5.0                    # enough for trigger + station name
DEMO = ["성균관대", "의왕"]        # plain stations, for the route demo


def read_wav(path: Path) -> np.ndarray:
    with wave.open(str(path), "rb") as w:
        return np.frombuffer(w.readframes(w.getnframes()), dtype=np.int16)


def main():
    n = int(CLIP_SEC * SR)
    clips = []
    for name in DEMO:
        p = WAV / f"{name}.wav"
        if not p.exists():
            sys.exit(f"음원 없음: {p}")
        a = read_wav(p)[:n]
        if len(a) < n:
            a = np.pad(a, (0, n - len(a)))
        clips.append((name, a))

    lines = [
        "// Auto-generated by scripts/gen_demo_audio.py — do not edit.",
        "// Demo announcement clips: int16 PCM, 16 kHz mono, Flash-resident.",
        "#ifndef DEMO_AUDIO_H",
        "#define DEMO_AUDIO_H",
        "",
        "#include <stdint.h>",
        "",
    ]
    for i, (name, a) in enumerate(clips):
        lines.append(f"// clip {i}: {name}  ({len(a)} samples, {len(a)/SR:.1f}s)")
        lines.append(f"static const int16_t demo_pcm_{i}[{len(a)}] = {{")
        for j in range(0, len(a), 20):
            row = ",".join(str(int(v)) for v in a[j:j + 20])
            lines.append(f"  {row},")
        lines.append("};")
        lines.append("")

    lines += [
        "typedef struct {",
        "  const char    *name;       // expected station (for demo display)",
        "  const int16_t *pcm;        // int16 PCM samples",
        "  int            n_samples;",
        "} DemoClip;",
        "",
        f"static const DemoClip demo_clips[{len(clips)}] = {{",
    ]
    for i, (name, a) in enumerate(clips):
        lines.append(f'  {{ "{name}", demo_pcm_{i}, {len(a)} }},')
    lines += [
        "};",
        f"#define NUM_DEMO_CLIPS {len(clips)}",
        "",
        "#endif  // DEMO_AUDIO_H",
        "",
    ]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    flash_kb = sum(len(a) for _, a in clips) * 2 / 1024
    print(f"firmware/demo_audio.h 생성 — {len(clips)}개 클립, 각 {CLIP_SEC}s")
    print(f"  Flash 사용: {flash_kb:.0f} KB  (음원 데이터만)")
    for name, a in clips:
        print(f"  - {name}: {len(a)} samples")


if __name__ == "__main__":
    main()
