// Auto-generated by scripts/gen_firmware_assets.py — do not edit.
// Path 1 model metadata: labels, normalization, pipeline thresholds.
#ifndef MODEL_META_H
#define MODEL_META_H

// ---- audio / feature ----
#define SAMPLE_RATE      16000
#define N_FFT            512
#define N_MELS           40
#define MEL_HOP          256

// ---- window sizes (samples) ----
#define KWS_WIN_SAMPLES  16000   // 1.0s
#define CNN_WIN_SAMPLES  32000   // 2.0s
#define KWS_MEL_FRAMES   63
#define CNN_MEL_FRAMES   126

// ---- per-model log-mel normalization (x = (mel - mean) / std) ----
#define KWS_NORM_MEAN    (-28.34517288f)
#define KWS_NORM_STD     (18.41120529f)
#define CNN_NORM_MEAN    (-25.46396637f)
#define CNN_NORM_STD     (14.81447697f)

// ---- pipeline (same as verify_pipeline.py) ----
#define SLIDE_HOP_SAMPLES   4000   // 0.25s KWS slide
#define NAME_OFFSET_SAMPLES 24000   // trigger start -> station name
#define TRIG_THRESH         (0.6f)             // KWS trigger probability
#define CONF_THRESH         (0.5f)             // min CNN confidence
#define MIN_TRIG_RUN        3               // debounce: consecutive trigger windows

// ---- station labels (CNN output index -> name, UTF-8) ----
#define NUM_STATIONS 14
static const char *const STATION_NAMES[NUM_STATIONS] = {
  "가산디지털단지",
  "관악",
  "구로",
  "군포",
  "금정",
  "금천구청",
  "당정",
  "독산",
  "명학",
  "석수",
  "성균관대",
  "신도림",
  "안양",
  "의왕"
};

#endif // MODEL_META_H
